baseURL = "https://dawsonfairbanks.com/"
languageCode = "en-us"
title = "Dawson Fairbanks"
theme = "simple"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Dawson Fairbanks"
  description = "Postdoctoral Researcher | Biogeochemist | Microbial Ecologist"
  favicon = "favicon.ico"

  [[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    url = "https://github.com/dawsonfairbanks"

  [[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    url = "mailto:dawson@example.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/research"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/#lets-connect"
    weight = 4
